---
- name: Filter servers based on kernel version
  hosts: dev
  gather_facts: true
  
  vars:
    kernel_version: "{{ kernel_version }}" #"5.4.0-1110-aws"
    reference_kernel_version: "5.4.0-1110-aws"

  tasks:
    - name: remove files
      command: rm -rf /home/saswat.beurik/upgrade/server_list.txt
      delegate_to: localhost
      tags: Download_Report

    - name: Get kernel version
      shell: uname -r
      register: kernel_version_output
      tags: Download_Report

    - name: Set kernel upgrade status
      set_fact:
        kernel_upgrade_status: "{{ 'Desired' if kernel_version_output.stdout == reference_kernel_version else 'Not_Desired' }}"
      tags: Download_Report

    - name: Debug current and input kernel versions
      debug:
        msg:
          - "Current Kernel Version: {{ kernel_version_output.stdout }}"
          - "Input Kernel Version: {{ kernel_version }}"
      tags: Download_Report

    - name: Fetch Ubuntu Release Status
      shell: pro security-status
      register: ubuntu_security_status_output
      tags: Download_Report

    - name: Determine Ubuntu status based on the command output
      set_fact:
        ubuntu_release_status: "{{ 'Ubuntu Pro' if 'This machine is attached to an Ubuntu Pro subscription' in ubuntu_security_status_output.stdout else 'Ubuntu Standard' }}"
      tags: Download_Report

    - name: Get Unattended Upgrades status
      command: systemctl status unattended-upgrades.service
      register: unattended_upgrades_status
      ignore_errors: true
      tags: Download_Report

    - name: Set Unattended Upgrades status as a fact
      set_fact:
        unattended_upgrades_status: "{{ 'active' if unattended_upgrades_status.rc == 0 and 'Active: active (running)' in (unattended_upgrades_status.stdout | default('')) else 'inactive' }}"
      tags: Download_Report

    - name: Filter servers with upgraded kernel
      local_action: shell echo "{{ inventory_hostname }} {{ ansible_distribution_version }} {{ ansible_kernel }} {{ ubuntu_release_status }} {{ kernel_upgrade_status }} {{ unattended_upgrades_status }}" >> server_list.txt
      tags: Download_Report

    - name: Convert server_list.txt to server_list.csv and save with timestamp
      shell: |
        timestamp=$(date "+%Y-%m-%d_%H-%M-%S")
        sed 's/ \| /,/g' /home/saswat.beurik/upgrade/server_list.txt > "/home/saswat.beurik/upgrade/server_list_$timestamp.csv"
        rm -f /home/saswat.beurik/upgrade/server_list.txt
      register: convert_result
      delegate_to: localhost
      tags: Download_Report

    - name: Display message indicating CSV download
      debug:
        msg: "CSV file has been generated and saved as server_list_{{ convert_result.end.split('.')[0] }}.csv"
      tags: Download_Report
