---
- name: compatibility check
  hosts: "{{ cli_hosts }}"
  tasks:
    - name: Run 'dpkg -l' command to list installed packages
      shell: dpkg -l
      register: package_list

    - name: Create a file with package list on the localhost
      copy:
        content: "{{ package_list.stdout }}"
        dest: "installed_packages_{{ ansible_fqdn }}.txt"
      delegate_to: localhost
