#Purpose This playbook is used to configure mail to send attachment.
#how to run the playbook: ansible-playbook2 ansible2/adhoc_playbooks/mail_config.yml -e 'cli_hosts=tag_Name_<hostname> cli_cloud_provider=ec2 cli_ec2_dc_switch=<n-virginia|beijing>' --vault-password-file ~/.vault -D

- name: Send Server info through mail
  hosts: localhost
  vars_files:
    - ../vars_files/secrets.yml
  vars:
    ses_zaphod_nv_username: "{{ ses_zaphod_nv_username }}"
    ses_zaphod_nv_password: "{{ ses_zaphod_nv_password }}"

  tasks:

      - name: extract latest file
        shell: basename $(ls -1t /tmp/Server* | head -1)
        register: csv_results

      - name: Sending an e-mail using AWS SES
        mail:
          host: email-smtp.us-west-2.amazonaws.com
          port: 465
          username: "{{ ses_zaphod_nv_username }}"
          password: "{{ ses_zaphod_nv_password }}"
          to: "devops@saswat.com,saswat.beurik@gmail.com"
          subject: "Daily report {{ ansible_date_time.date }}"
          body: "Hi,\n \
                 Please find the attached CSV file.\n \

                 Best regards,\n \
                 Devops Team"
          from: saswat@ops.com
          secure: starttls
          attach: "/tmp/{{ csv_results.stdout }}"
